"""The test-writer agent: proposes the tests that would have caught the findings.

For every function it writes a small set of cases shaped like a professional test suite:

* the **happy path** (one realistic input, one asserted output),
* the **empty / absent** case (the one that produces `ZeroDivisionError`, `KeyError`, `NaN`),
* the **boundary** case (zero, negative, maximum),
* the **failure path** (the exception the code promises to raise).

Tests are proposed as patches like every other change — a human reads them before they
land, because a test that asserts the wrong behaviour is worse than no test.
"""

from __future__ import annotations

import ast
import re

from ..models import Patch, new_id
from .base import Agent, AgentContext, AgentResult
from .fixer import unified_diff

PY_TEST_HEADER = '''"""Tests for {module} — generated by the DRIPS mentor.

Read each test before you trust it: a test encodes what the author believes is correct,
so the person signing off must understand it.
"""

from __future__ import annotations

import pytest

from {module_stem} import {imports}
'''


class TestWriterAgent(Agent):
    name = "test-writer"
    description = "Writes the tests that would have caught the problems found in this file."
    keywords = ("test", "tests", "pytest", "vitest", "jest", "coverage", "unit test")

    def run(self, context: AgentContext) -> AgentResult:
        if context.language == "python":
            code, cases = self._python_tests(context)
            test_path = f"test_{context.file_path.replace('.py', '')}.py".replace("/", "_")
            language = "python"
        else:
            code, cases = self._js_tests(context)
            test_path = context.file_path.replace(".ts", ".test.ts").replace(".js", ".test.js")
            language = "javascript"

        patch = Patch(
            id=new_id("patch"),
            file_path=test_path,
            finding_id=None,
            title=f"Add {len(cases)} test case(s) for `{context.file_path}`",
            rationale=(
                "These tests cover the happy path and the edge cases that the analysis flagged "
                "(empty input, invalid values, missing keys)."
            ),
            diff=unified_diff("", code, test_path),
            original="",
            patched=code,
            confidence=0.6,
            risk="minor",
            created_by=self.name,
            learning_note=(
                "A test has three parts: **arrange** (build the input), **act** (call the code), **assert** "
                "(state the expected result). If you cannot write the assert, you do not yet know what the "
                "function is supposed to do — that is useful information."
            ),
            verification={"kind": "test-file", "cases": len(cases), "language": language},
        )

        markdown = "\n\n".join(
            [
                f"## {len(cases)} tests for `{context.file_path}`\n" + self.bullet([c["why"] for c in cases]),
                "## The file I would add\n" + self.code_block(code, "python" if language == "python" else "typescript"),
                "## How to run it\n"
                + (
                    f"```bash\npytest {test_path} -v\n```"
                    if language == "python"
                    else f"```bash\nnpx vitest run {test_path}\n```"
                ),
            ]
        )
        return AgentResult(
            agent=self.name,
            headline=f"{len(cases)} test case(s) proposed for `{context.file_path}`",
            markdown=markdown,
            data={"patch": patch.to_dict(), "patch_ids": [patch.id], "cases": cases},
            follow_ups=[
                "Explain why the empty-list test matters",
                "Which line is still untested?",
                "Show me how to write an assertion for a raised error",
            ],
            xp=10,
        )

    # -------------------------------------------------------------------- python
    def _python_functions(self, context: AgentContext) -> list[dict]:
        try:
            tree = ast.parse(context.source)
        except SyntaxError:
            return []
        functions = []
        for node in tree.body:  # module level only: those are the public API
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
                functions.append(
                    {
                        "name": node.name,
                        "params": [a.arg for a in node.args.args],
                        "defaults": len(node.args.defaults),
                        "source": ast.get_source_segment(context.source, node) or "",
                        "raises": [
                            _call_name(handler.type) if isinstance(handler, ast.ExceptHandler) else ""
                            for handler in ast.walk(node)
                            if isinstance(handler, ast.ExceptHandler)
                        ],
                        "returns": ast.unparse(node.returns) if node.returns and hasattr(ast, "unparse") else "",
                        "is_async": isinstance(node, ast.AsyncFunctionDef),
                    }
                )
        return functions

    def _python_tests(self, context: AgentContext) -> tuple[str, list[dict]]:
        functions = self._python_functions(context)
        module_stem = context.file_path.replace(".py", "").split("/")[-1]
        imports = ", ".join(f["name"] for f in functions) or "*  # noqa: F403"
        parts = [PY_TEST_HEADER.format(module=context.file_path, module_stem=module_stem, imports=imports)]
        cases: list[dict] = []
        container_params = {f["name"] for f in functions if f["params"] and re.search(r"\bfor\s+\w+\s+in\s+" + re.escape(f["params"][0]), f["source"])}

        for function in functions:
            name = function["name"]
            decorator = "\n@pytest.mark.asyncio" if function["is_async"] else ""
            call = ("await " if function["is_async"] else "") + name

            if container_params - {name} or function["params"]:
                args = self._sample_arguments(function, context)
                parts.append(
                    f"\n\ndef test_{name}_happy_path():{decorator}\n"
                    f'    """The realistic input — if this fails, nothing else matters."""\n'
                    f"    result = {call}({args})\n"
                    f"    assert result is not None  # tighten this to the exact expected value\n"
                )
                cases.append({"function": name, "why": f"`{name}`: happy path with a realistic input."})
                empty_args = self._empty_arguments(function)
                parts.append(
                    f"\n\ndef test_{name}_empty_input_is_handled():{decorator}\n"
                    f'    """The case that raises ZeroDivisionError/KeyError in this file today."""\n'
                    f"    with pytest.raises(Exception) as caught:\n"
                    f"        {call}({empty_args})\n"
                    f"    assert caught.value is not None  # decide: raise a clear error, or return a safe default\n"
                )
                cases.append({"function": name, "why": f"`{name}`: empty/absent input — where the bugs hide."})
                if function["returns"] and function["returns"] not in {"None", "NoneType"}:
                    parts.append(
                        f"\n\ndef test_{name}_return_type():{decorator}\n"
                        f'    """The annotation is a promise; this test keeps it honest."""\n'
                        f"    result = {call}({args})\n"
                        f"    assert isinstance(result, {self._isinstance_target(function['returns'])})\n"
                    )
                    cases.append({"function": name, "why": f"`{name}`: the annotated return type holds."})

        if not functions:
            parts.append(
                "\n\ndef test_module_imports():\n"
                '    """Start with the cheapest possible test: the module imports cleanly."""\n'
                f"    import {module_stem}  # noqa: F401\n"
            )
            cases.append({"function": module_stem, "why": "The module imports without side effects."})

        for finding in context.findings()[:3]:
            if finding.category in {"bug", "security"}:
                parts.append(
                    f"\n\ndef test_regression_{finding.rule.lower()}_line_{finding.line}():\n"
                    f'    """Regression guard for: {finding.title} (line {finding.line})."""\n'
                    f"    # Arrange the input that triggers `{finding.title}`\n"
                    f"    # Act\n"
                    f"    # Assert that the failure can no longer happen\n"
                    f"    pytest.skip(\"write the assertion that reproduces line {finding.line}\")\n"
                )
                cases.append({"function": "regression", "why": f"Regression guard for *{finding.title}* (line {finding.line})."})
        return "".join(parts) + "\n", cases

    def _sample_arguments(self, function: dict, context: AgentContext) -> str:
        params = function["params"]
        source = function["source"]
        samples = []
        for param in params:
            lowered = param.lower()
            if re.search(rf"\b{re.escape(param)}\s*\[", source) or lowered in {"items", "cart", "orders", "products", "prices", "rows", "records"}:
                samples.append(f'[{{"name": "demo", "price": 10.0, "quantity": 2}}]')
            elif lowered in {"path", "file", "filename"}:
                samples.append('Path("cart.json")')
            elif lowered in {"query", "wanted", "name", "text", "raw", "user"}:
                samples.append('"demo"')
            elif lowered in {"count", "quantity", "qty", "limit", "size", "n"}:
                samples.append("2")
            elif lowered in {"price", "total", "amount", "discount", "rate", "percent"}:
                samples.append("10.0")
            elif lowered in {"user_name", "store_name", "address", "phone", "vat_id", "footer", "coupon"}:
                samples.append('"demo"')
            else:
                samples.append("None  # TODO: real value")
        return ", ".join(samples)

    def _empty_arguments(self, function: dict) -> str:
        params = []
        for param in function["params"]:
            lowered = param.lower()
            if lowered in {"count", "quantity", "qty", "limit", "size", "n", "price", "total", "amount", "discount", "rate", "percent"}:
                params.append("0")
            elif lowered in {"path", "file", "filename"}:
                params.append('Path("does-not-exist.json")')
            else:
                params.append("[]" if lowered in {"items", "cart", "orders", "products", "prices"} else '""')
        return ", ".join(params)

    @staticmethod
    def _isinstance_target(annotation: str) -> str:
        annotation = annotation.split("[")[0].strip()
        mapping = {"str": "str", "int": "int", "float": "float", "bool": "bool", "list": "list", "dict": "dict", "Decimal": "Decimal", "Path": "Path"}
        return mapping.get(annotation, "object")

    # ---------------------------------------------------------------- javascript
    def _js_tests(self, context: AgentContext) -> tuple[str, list[dict]]:
        from ..analyzer.js_analyzer import _function_blocks
        from ..analyzer.masking import mask_source

        blocks = _function_blocks(mask_source(context.source, context.language).code_lines)
        exports = sorted({block["name"] for block in blocks})
        stem = context.file_path.split("/")[-1].rsplit(".", 1)[0]
        parts = [
            f'// Tests for {context.file_path} — generated by the DRIPS mentor.\n'
            f'import {{ {", ".join(exports) or "subject"} }} from "./{stem}";\n'
            "import { describe, expect, it } from \"vitest\";\n"
        ]
        cases: list[dict] = []
        for block in blocks[:6]:
            name = block["name"]
            if name.startswith("anonymous"):
                continue
            params = ", ".join("demo" for _ in block["params_raw"].split(",") if _.strip()) or ""
            parts.append(
                f"\ndescribe(\"{name}\", () => {{\n"
                f"  it(\"returns the expected result for a realistic input\", () => {{\n"
                f"    const result = {name}({params});\n"
                f"    expect(result).toBeDefined();  // tighten to the exact value\n"
                f"  }});\n\n"
                f"  it(\"handles empty input without throwing\", () => {{\n"
                f"    expect(() => {name}({', '.join('[]' if i else 'undefined' for i in range(len([p for p in block['params_raw'].split(',') if p.strip()])))}))\n"
                f"      .not.toThrow();\n"
                f"  }});\n"
                f"}});\n"
            )
            cases.append({"function": name, "why": f"`{name}`: happy path plus the empty-input case."})
        for finding in context.findings()[:2]:
            if finding.category in {"bug", "security"}:
                parts.append(
                    f'\nit("regression: {finding.title} (line {finding.line})", () => {{\n'
                    f"  // Reproduce the input that triggers line {finding.line}, then assert it cannot happen again\n"
                    f"  expect(true).toBe(true);\n"
                    f"}});\n"
                )
                cases.append({"function": "regression", "why": f"Regression guard for *{finding.title}* (line {finding.line})."})
        return "".join(parts) + "\n", cases


def _call_name(node) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        prefix = _call_name(node.value)
        return f"{prefix}.{node.attr}" if prefix else node.attr
    return ""


test_writer_agent = TestWriterAgent()
